name: Tests CI

on:
  pull_request:
    branches:
      - main 

jobs:
  execute-test-suite:
    runs-on: ubuntu-latest
    name: Run Test Suite
    steps:
    - name: Run tests
      with:
        script: npm install && npm test
  
